
services:

  php-apache:
    volumes:
      - ./.docker/php-apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php-apache/apache2.conf:/etc/apache2/apache2.conf
      - ./.docker/php-apache/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9080:80"
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app
###< symfony/mailer ###

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - "27017:27017"
    env_file:
      - .env.local
    environment:
      - MONGODB_INITDB_DATABASE=app
      - MONGODB_INITDB_ROOT_USERNAME=app
      - MONGODB_INITDB_ROOT_PASSWORD=!ChangeMe!
###< doctrine/mongodb-odm-bundle ###
