controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    methods: ['POST']

wildcard_404:
  path: '/{any}'
  controller: App\Controller\IndexConrtoller::index
  requirements:
    any: .*
